### ISSUE TITLE
Be the One

### ISSUE THREAD

**Issue by ashwinitanpure** [ashwinitanpure/DSAlgorithms#1]
Write an algorithm to determine if a number satisfies following condition.

Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number is equal to 1, or it loops endlessly in a cycle which does not include 1.

**Comment by amaan-ahmad** [comment]
Hey @ashwinitanpure, I am interested in contributing to this issue. Kindly assign it to me 😊

**Comment by amaan-ahmad** [comment]
@ashwinitanpure, I was curious to solve it, so **I did make a pull request**. Kindly merge 😁 and check if it's okay 😅

**Comment by TanviSutar** [comment]
@ashwinitanpure i found this very similar to happy number, kindly review my code and merge.
